### PR TITLE
MNT: rerender

### LINKED ISSUE #4: @conda-forge-admin, please rerender
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #4.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #4

### CODE REVIEW

**Comment by asmeurer** [comment]
I guess the build number has to be bumped manually?

I need this for compatibility with an upstream fix https://github.com/conda-forge/emacs-feedstock/pull/27 @pkgw @epruesse

**Comment by pkgw** [comment]
FYI, gonna let this marinate a bit while Travis works out its problems.

**Comment by asmeurer** [comment]
OK. Thanks for the help.

**Comment by pkgw** [comment]
Closing/reopening to try to get more CI to run.

**Comment by pkgw** [comment]
I'm not sure where AppVeyor went here, but good enough for me.

**Comment by asmeurer** [comment]
The Circle build on master failed https://circleci.com/gh/conda-forge/xorg-libxft-feedstock/16

**Comment by asmeurer** [comment]
This is the error

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

**Comment by asmeurer** [comment]
Maybe it's just an intermittent issue with GitHub. Can you try rebuilding or pushing a bump commit to master.

**Pull request merged**
